language: cpp
os: linux
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - lcov

stages:
  - "compile"
  - "test"

jobs:
  include:
    - stage: "compile"
      name: "Generate build files"
      script: ./build.sh init
    - name: "Compile 'qualitair'"
      script: ./build.sh qualitair
    - name: "Compile 'utests'"
      script: ./build.sh utests
    - stage: "test"
      name: "Unit tests"
      script: ./bin/utests

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"