language: cpp
os: linux
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - lcov

script:
  - ./build.sh
  - ./bin/utests

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

