language: cpp
os: linux
compiler: gcc
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov
      - gcc-7
      - g++-7

stages:
  - "compile"
  - "test"
  - "release"

before_script:
  - ./build.sh init

jobs:
  include:
    - stage: "compile"
      name: "Compile 'qualitair'"
      script: ./build.sh qualitair
    - name: "Compile 'utests'"
      script: ./build.sh utests

    - stage: "test"
      name: "Unit tests"
      script:
      - ./build.sh utests
      - ./bin/utests
      - ./coverage.sh

    - stage: "release"
      name: "github-release"
      script:
        - cd installer
        - ./create-installer.sh
        - cd ..
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file:
          - qualitair.zip
        on:
          tags: true


