language: cpp
os: linux
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - lcov

stages:
  - "compile"
  - "test"

before_script:
  - ./build.sh init

jobs:
  include:
    - stage: "compile"
      name: "Compile 'qualitair'"
      script: ./build.sh qualitair
    - name: "Compile 'utests'"
      script: ./build.sh utests

    - stage: "test"
      name: "Unit tests"
      script:
      - ./build.sh utests
      - ./bin/utests
      - ./coverage.sh

