language: cpp
os: linux
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - lcov

stages:
  - "compile"
  - "test"

before_script:
  - ./build.sh init

jobs:
  include:
    - stage: "compile"
      name: "Compile 'qualitair'"
      script: ./build.sh qualitair
    - stage: "test"
      name: "Compile 'utests'"
      script:
      - ./build.sh utests
      - ./bin/utests

#script:
#  - ./build.sh qualitair
#  - ./build.sh utests
#  - ./bin/utests

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"