
ignore:
  - "deps"
  - "tests"
  - "lib"
  - "bin"
  - "src/Data/src/Measurement.cpp"
  - "src/Data/src/Sensor.cpp"
  - "src/Data/src/Attribute.cpp"
  - "scr/Data/src/IData.cpp"
  - "scr/ETL/src/IETL.cpp"
  - "scr/DataProcessor/src/IDataProcessor.cpp"
  - "scr/DataProcessor/src/IDataProcessor.cpp"
  - "scr/View/src/IOutput.cpp"